// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qbyglwscvslwtutrdvyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFieWdsd3NjdnNsd3R1dHJkdnlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyNTAxNDIsImV4cCI6MjA5MzgyNjE0Mn0.vbn6ZNs8OP5-SmRNhJVkg1GgSKIsY4yidgVQqxQiNYU";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);